project:
  type: website
  output-dir: docs

website:
  title: "Louis M. Penrod, Ph.D."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Bio
        href: bio.qmd
      - text: Projects
        href: projects.qmd
      - text: Resources
        href: resources.qmd
    right: 
      - icon: github
        href: https://github.com/LouisMPenrod 
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-link: true
    code-tools: true



